//
//  MantrasModel.swift
//  Mantra
//
//  Created by Karaimchuk on 27.09.21.
//

import Foundation

class MantrasModel {
  
  public let mantraTextArr = [
    "The greatest sacred sound, the symbol of Trimurti, the original vibration from which the universe arose. It is believed that the one who utters “Om” creates an invisible shield around him that drives away evil. “Om” gives good to all living beings and returns to the original point of being, to nirvana where freedom, immortality and love reign",
    "It is pronounced like this:\nOm Bhur Bhuvah Svaha\nTat Savitur Varenyam\nBhargo Devasya Dhimahi\nDhiyo Yonah Prachodayat\nThis mantra sounds like an appeal to the cosmological symbols of Hinduism: heaven, earth and air. The name of Savitar, the sun god, is mentioned. A call to direct your thoughts to the shining deities.\nGayatri is one of the forms of Saraswati. In this form, she helps sentient beings achieve enlightenment and liberation from karma. Kind and forgiving Gayatri hears everyone who recites the mantra dedicated to her. One of the famous performances of this mantra is from the lips of Sai Baba",
    "Om Shrim Hrim Klim Glaum Gum\nGanapataye Vara Varada Sarva Janam\nMe Washanamaya Svaha\nOh, lord of the gana, bestowing gifts, removing the obstacles of every person, bring liberation to me too.\nGanesha, the son of Parvati and Shiva, is considered a symbol of wealth and wisdom. By repeating the Ganesha mantra a person seems to give his problems to him. Ganesha always comes to the rescue, giving calmness, getting rid of fears, he destroys illusions",
    "Gurur Brahma Gurur Vishnu\nGuru Devo Maheswaraha\nGuru Saakshat Param Brahma\nTasmai Shriy Gurave Namaha\nOh great teachers Brahma, Vishnu and Shiva (Maheswara)! My earthly guru is your messenger, and I worship him as I worship you.\nIn those moments when a person is lost and does not know the answers to questions, he can ask for help. Help comes from teachers, sages, deities and common people. To heal from ailments, you need to read the guru mantra daily, mentally addressing the person from whom help is required",
    "The mantra for attracting well-being to the house is pronounced like this:\nOm Shrim Mahalakshmie Namaha\nMy greetings to the great Lakshmi, who bestows prosperity.\nThis is an appeal to the goddess Lakshmi, who is responsible for prosperity, wealth, generosity. By chanting her name, a person attracts money and necessary material goods. The mantra must be recited with utmost honesty and sincerity",
    "Asato Maa Sat Gamaya\nTamaso Maa Jyotir Gamaya\nMrityor Maa Amritam Gamaya\nLead me from false to true, from darkness to light, from death to immortality, oh eternal rest.\nThey say that this mantra is so strong that even a person listening to it receives gifts of fate and purifies his karma. She is able to throw away sadness, get rid of diseases and tune in a positive way",
    "Om Mani Padme Hum\nOm, the pearl in the lotus flower.\nOne of the most famous Buddhist mantras in the world, it personifies boundless love, forgiveness and enlightenment. Turning over the rosary in his hands and reciting the mantra of love at least several times 108, a person fills his heart with light, gets rid of the ego, gets into the space of higher vibrations",
    "Ra Ma Da Sa\nI worship the sun, moon, earth and space.\nThis mantra is useful for those who suffer from diseases and ailments. Concentrating on a problem point in the body or mind, the health mantra should be repeated daily for 20-30 minutes in order to feel relief in a week",
    "Om Namah Shivaya\nI worship you, oh great Shiva.\nThe legendary mantra addressed to the god Shiva gives incredible strength and energy to the one who will pronounce it with all sincerity, soul and dedication. Shiva is capable of destroying the universe, but he is very kind and supportive to those who worship him. He hears every word and every request, he is ready to give everything that he has",
    "Om Tare Tuttare Ture Sokha\nOm, removal from earthly attachments, deliverance from suffering, elimination of ignorance, purification of the past.\nThe second most important mantra in Buddhism. Turning to the mother of all Buddhas, Green Tara, is like turning to your own mother. She will protect, regret, warm, feed and give all her love. Not every person has the opportunity to come under the wing of their mother, therefore thousands of people around the world turn to Green Tara. She helps and protects",
    "Om Sat Chit Ananda Parabrahma\nPurushotama Paramathama\nSri Bhagavati Samitha\nSri Bhagavate Namaha\nOm, I worship the all-pervading being, pure consciousness, bliss, the creator of the universe, the material form of the divine, the immaterial form of the divine, the feminine principle in union with the masculine principle, I worship the entire universe.\nThis mantra for negativity is so powerful that it works even for those who do not know its meaning. Delicate and melodic, it surrounds the person who pronounces it with affection and kindness. Negativity, troubles, dangerous influence from the outside will no longer be able to disturb you and your loved ones",
    "Hare Krishna Hare Krishna\nKrishna Krishna Hare Hare\nHare Rama Hare Rama\nRama Rama Hare Hare\nDelusional, all-attractive, all-pleasing, let me serve you.\nThe main mantra of the Hare Krishnas. The Mahamantra stops endless internal dialogue, calms the mind, opens the heart and allows divine light to permeate the body"
  ]
  
  public let mantraImageArr = ["Mantra-Om", "Gayatri-mantra", "Mantra-Ganeshi", "Guru-mantra", "Mantra-bogatstva", "Mantra-ochishcheniya", "mantra-lyubvi", "Mantra-zdorovya", "Mantra-energii-i-sily", "Mantra-Zelenoy-Tary", "Mula-mantra", "Makhamantra-Khare-Krishna"]
  
  public let mantraTitleArr = ["Mantra Om", "Gayatri Mantra", "Mantra of Ganesha", "Guru mantra or healing mantra", "The mantra of wealth and money", "Mantra of Purification", "Mantra of love", "Mantra of health", "Mantra of energy and strength", "Mantra of Green Tara", "Mula mantra or mantra for getting rid of negativity", "Mahamantra Hare Krishna"]
}
